ZSH=$HOME/.oh-my-zsh
ZSH_THEME="bira"
plugins=(git bundler sublime)
source $ZSH/oh-my-zsh.sh

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"




########################
# User Exports #########
########################

eval "$(rbenv init -)"

export PATH="/usr/local/heroku/bin:$HOME/.rbenv/shims:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

export EDITOR='nano'